### ISSUE TITLE
Unable to add new user and go beyond that

### ISSUE THREAD

**Issue by sudiptabiswas22** [ashishrawat2911/firekart_app#5]
![image](https://user-images.githubusercontent.com/25134017/101480458-bd054f80-3979-11eb-8e2b-33060b4d720f.png)
Once I write some name in the field, it should ideally take me to the next step. However, nothing happens after I click on the 'Add' button.
Following is the terminal response I received.
![image](https://user-images.githubusercontent.com/25134017/101480680-08b7f900-397a-11eb-95c1-254c481b0f36.png)

**Comment by ashishrawat2911** [comment]
Hi, It was a router issue, I have fixed it
