### ISSUE TITLE
query regarding no of reads

### ISSUE THREAD

**Issue by SriRamGovardhanam** [ashishrawat2911/firekart_app#6]
Hi Ashish,

Backend structure is really great, thank you for sharing your work
Can you tell us what is the average no of reads when a customer opens the app for the 1st time, have you created any cache functionality while implementing?
A response would be much appreciated

**Comment by ashishrawat2911** [comment]
Hi , No I have not created the cache functionality , Its is using the default firebase caching but I am planning to implement rest apis , I am working on it
