### ISSUE TITLE
Dashboard Error - No products showing but error

### ISSUE THREAD

**Issue by Techxjunkie** [ashishrawat2911/firekart_app#82]
type 'Null' is not a subtype of type 'String' in type cast
No products are showing on the dashboard or when selecting View All products but only this error is on the dashboard.
This is the error I receive after logging into the application.  Firebase is setup correctly also with screenshot to verify.  Any help is appreciated.

![Screenshot 2023-05-17 at 9 51 13 PM](https://github.com/ashishrawat2911/flutter_commerce/assets/89175625/944c27ea-1b9e-42c9-8ece-83dd65b1d29a)
![Screenshot 2023-05-18 at 7 42 38 AM](https://github.com/ashishrawat2911/flutter_commerce/assets/89175625/9da0c490-6013-4e57-8c79-808afaf3afc1)

**Comment by Techxjunkie** [comment]
This is dashboard error I am receiving:  I changed it to a string instead of null but I am receiving the same error?

 DashboardState(dealOfTheDay: ResultState<List<Product>>.loading(), onSale: ResultState<List<Product>>.error(error: type 'Null' is not a subtype of type 'String' in type cast), topProducts: ResultState<List<Product>>.loading())

**Comment by Techxjunkie** [comment]
Also here is Flutter error when loading the application concerning same issue:
flutter: type 'Null' is not a subtype of type 'ResultState<List<Product>>' in type cast

**Comment by ashishrawat2911** [comment]
Hi,
This issue has been fixed
